version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/mlbapi
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: ec2-user
