version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: /home/ec2-user/mlbapi-codedeploy-scripts/before_install.sh
    - location: /home/ec2-user/mlbapi-codedeploy-scripts/export_secrets.sh
    - runas: ec2-user
  AfterInstall:
    - location: /home/ec2-user/mlbapi-codedeploy-scripts/after_install.sh
      timeout: 180
    - runas: ec2-user
