version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Installing dependencies"
      - sudo yum install -y git gcc python3-devel python3-pip python-virtualenv
      - pip install -r requirements.txt
  build:
    commands:
      - ./manage.py test tests/
  post_build:
    commands:
      - echo Build completed on `date`